name: Desktop Reusable Release Workflow

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string

jobs:

  Linux-AppImage:
    name: Linux AppImage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: yarn install --immutable

      - name: Rebuild Electron Native Modules
        run: yarn workspace @standardnotes/desktop rebuild:home-server

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - name: Compile for AppImage
        run: yarn run webpack --config desktop.webpack.prod.js
      - name: AppImage
        run: |
          yarn run electron-builder --linux --x64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: AppImageX64
        run: |
          yarn run electron-builder --linux --x64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      - name: AppImageArm64
        run: |
          yarn workspace @standardnotes/desktop rebuild:home-server --arch arm64
          yarn run electron-builder --linux --arm64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
        env:
          npm_config_target_arch: 'arm64'

      - name: Upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: dist-linux-appimage
          path: |
            packages/desktop/dist/*.AppImage
            packages/desktop/dist/*.yml
            packages/desktop/dist/*.yaml

  Linux-Dir:
    name: Linux Dir
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: yarn install --immutable

      - name: Rebuild Electron Native Modules
        run: yarn workspace @standardnotes/desktop rebuild:home-server

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - name: Dir
        run: |
          yarn run webpack --config desktop.webpack.prod.js
          yarn run electron-builder --linux --x64 -c.linux.target=dir --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      - name: DirArm64
        run: |
          yarn workspace @standardnotes/desktop rebuild:home-server --arch arm64
          yarn run webpack --config desktop.webpack.prod.js
          yarn run electron-builder --linux --arm64 -c.linux.target=dir --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
        env:
          npm_config_target_arch: 'arm64'

  Linux-Deb:
    name: Linux Deb
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: yarn install --immutable

      - name: Rebuild Electron Native Modules
        run: yarn workspace @standardnotes/desktop rebuild:home-server

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - name: Deb
        run: |
          yarn run webpack --config desktop.webpack.prod.js --env deb
          yarn run electron-builder --linux --x64 -c.linux.target=deb --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      - name: DebArm64
        env:
          npm_config_target_arch: 'arm64'
          USE_SYSTEM_FPM: 'true'
        run: |
          yarn workspace @standardnotes/desktop rebuild:home-server --arch arm64
          yarn run webpack --config desktop.webpack.prod.js --env deb
          yarn run electron-builder --linux --arm64 -c.linux.target=deb --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: dist-linux-deb
          path: |
            packages/desktop/dist/*.deb
            packages/desktop/dist/*.yml
            packages/desktop/dist/*.yaml

  Linux-Snap:
    name: Linux Snap
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: yarn install --immutable

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1

      - name: Install Review Tools
        run: sudo snap install review-tools

      - name: Package Snap
        run: |
          yarn run webpack --config desktop.webpack.prod.js --env snap
          yarn run electron-builder --linux --x64 -c.linux.target=snap --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Review Snap
        run: review-tools.snap-review dist/standard-notes-${{ env.APP_VERSION }}-linux-amd64.snap

      - name: Upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: dist-linux-snap
          path: |
            packages/desktop/dist/*.snap
            packages/desktop/dist/*.yml
            packages/desktop/dist/*.yaml

  Publish:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    if: ${{ always() }}
    needs: [Linux-AppImage, Linux-Dir, Linux-Deb, Linux-Snap]
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - run: yarn install --immutable

      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: packages/desktop/dist
          merge-multiple: true

      - name: Generate Checksums
        run: node scripts/sums.mjs

      - name: Generate Release Notes
        uses: ./actions/release-notes
        with:
          package: web desktop
        id: release-notes

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: '@standardnotes/desktop@${{ env.APP_VERSION }}'
          name: 'Desktop ${{ env.APP_VERSION }}'
          body: ${{ steps.release-notes.outputs.result }}
          prerelease: true
          draft: false
          files: packages/desktop/dist/*

  Notify:
    runs-on: ubuntu-latest
    needs: [Publish]
    steps:
      - name: Notify Release Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: releases-updated-event
