name: Mobile Release Production

on:
  push:
    tags:
      - '*standardnotes/web*'
  workflow_dispatch:

jobs:
  android:
    defaults:
      run:
        working-directory: packages/mobile
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Export version from package.json
        run:
          echo "PACKAGE_VERSION=$(grep '"version"' ../web/package.json | cut -d '"' -f 4 | cut -d "-" -f 1)" >> $GITHUB_ENV
      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install dependencies
        run: yarn install --immutable
      - run: yarn build:mobile

      - name: Generate Release Notes
        uses: ./actions/release-notes
        with:
          package: mobile
        id: release-notes
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          tag_name: "@standardnotes/mobile@${{ env.PACKAGE_VERSION }}"
          name: "Mobile ${{ env.PACKAGE_VERSION }}"
          body: ${{ steps.release-notes.outputs.result }}
          prerelease: true
          draft: false
          files: |
            packages/mobile/android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
            packages/mobile/android/app/build/outputs/apk/prod/release/app-prod-release.apk
